Initial commit: VestorlyApi wrapper gem
Initial structure and testing for login to vestorly api

Add advisor main API request for vestorly api

Basic structure for the the get request to the verstorly api to
request the advisor set

* TODO:
- Record CSV to upload
- Integrate with redail

Add ruby-redtail configuration

Fix problem with the ENV configuration variables when presenting
error:
  RuntimeError: can't modify frozen String

The issue was solved just by duplicating the strings of the values
using dup method of the string class

Add description and usage of the gem in the README.md

Add some examples and usage specifications to the README.md on the
VestorlyAPI objects

Add sign out api object and rename login to sign_in

Before the sign_in object was named as login, which was changed
to follow better the API description on the Vestorly API document

Add sign_out object to remove authentication token from Vestorly
system

Update add members api calls and update advisor structure

Add documentation to run the test and comment out redtail

Update the gem to remove redtail and add configuration

Add create_member method to advisor api

Change README.md description

The previous description talk about features not yet implemented
in this version of the gem

Update gemspec with dependencies versions

According to warning presented when trying to build the gem

Update README.md

[MAINTENANCE]: Update rspec version

Link license on the README.md

Add license on the markdown

Update LICENSE.txt